DROP DATABASE IF EXISTS ONLINE_STORE;

DROP SCHEMA IF EXISTS ONLINE_STORE;

CREATE SCHEMA IF NOT EXISTS ONLINE_STORE DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE ONLINE_STORE;

DROP DATABASE IF EXISTS ONLINE_STORE;

CREATE DATABASE ONLINE_STORE
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE ONLINE_STORE;

CREATE TABLE USERS(
User_ID int NOT NULL AUTO_INCREMENT,
Name varchar(128),
Surname varchar(128),
Email varchar(128) NOT NULL UNIQUE,
Phone int DEFAULT 0,
Login varchar(128) NOT NULL UNIQUE,
Password varchar(128) NOT NULL,
Account int DEFAULT 0,
Address varchar(128),
Town varchar(128),
ZipCode varchar(10),
PRIMARY KEY (User_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE GAMES(
Game_ID int NOT NULL AUTO_INCREMENT,
Image_ID int DEFAULT 0,
Title varchar(128) NOT NULL,
Type varchar(128) NOT NULL,
Description varchar(255) NOT NULL,
Price float NOT NULL DEFAULT 99.99,
PRIMARY KEY (Game_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE IMAGES(
ID int PRIMARY KEY AUTO_INCREMENT,
Image MEDIUMBLOB NOT NULL
);

CREATE TABLE ORDERS(
Order_ID int NOT NULL AUTO_INCREMENT,
User_ID int NOT NULL,
Game_ID int NOT NULL,
Amount int NOT NULL DEFAULT 1,
PRIMARY KEY (Order_ID),
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Game_ID) REFERENCES GAMES(Game_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE PAYMENTS(
Payment_ID int NOT NULL AUTO_INCREMENT,
Order_ID int NOT NULL,
Type_Payment varchar(255),
PRIMARY KEY (Payment_ID),
FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID)
);

CREATE TABLE SHIPMENTS(
Shipment_ID int NOT NULL AUTO_INCREMENT,
Order_ID int NOT NULL,
Type_Shipment varchar(255),
PRIMARY KEY (Shipment_ID),
FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID)
);

