			<div id="content">		 <!--treść strony, póki co pusta, ale proponuję może jakieś podglądy kategorii albo jakieś zestawienia kilku ostatnio dodanych bądź najczęściej kupowanych? -->
					<div id="adSlideshow"><img src="templates/images/reklama.jpg"></div>
					<br /><br />
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquet iaculis sem, ac bibendum justo sagittis a. Sed imperdiet dui tellus, in ornare urna eleifend accumsan. Cras id placerat est, ut ullamcorper tortor. Donec in tincidunt magna. Morbi risus mauris, condimentum non turpis quis, lobortis viverra arcu. Pellentesque volutpat aliquam lectus, a tempor sem mollis ac. Aliquam erat volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam eget dictum libero. Nullam efficitur, nisl a convallis facilisis, sem tortor maximus est, eu blandit metus quam eu lectus. Quisque laoreet consectetur laoreet. Proin egestas, arcu eget rutrum iaculis, purus libero luctus ante, in condimentum tellus velit sit amet orci. Cras orci odio, dictum non pharetra a, rutrum nec libero.<br /><br />

									Nam sodales nunc in elit accumsan accumsan. Pellentesque nunc felis, maximus eget lectus at, sodales malesuada tortor. Suspendisse at rutrum metus, id facilisis mi. Nulla vestibulum augue vitae elit ultricies lacinia. Curabitur sed sapien nibh. In dictum magna et odio commodo, vel scelerisque est porta. Cras at ultricies purus, in iaculis mi. Ut rutrum lorem at sapien accumsan, viverra gravida felis elementum. Vestibulum non ex eget eros blandit aliquet. Suspendisse aliquam orci risus, et ullamcorper mi sodales ornare. Nam ligula augue, tristique a aliquet maximus, eleifend nec ante.<br /><br />

									Integer rutrum ante purus, quis ultricies lorem interdum sit amet. Nunc vitae quam est. Praesent cursus vehicula gravida. In elit nisi, tristique a scelerisque mollis, viverra a urna. Donec quis sem diam. Morbi convallis elit ornare eleifend fermentum. Duis maximus dui velit, ut accumsan arcu sollicitudin id. Cras a ornare mi, quis imperdiet massa. Suspendisse commodo id nulla id pellentesque. Sed id dolor eleifend dolor faucibus euismod. Nunc finibus nisi massa, et varius leo tempus a. Mauris eget tristique diam, sed vestibulum augue. Mauris fermentum leo at ex fringilla, vel condimentum mauris cursus. Mauris ultrices sollicitudin tristique. Donec interdum enim at dui rhoncus, ut feugiat magna aliquet.<br /><br />

									Maecenas justo lectus, luctus vitae erat ut, venenatis feugiat ipsum. Sed sollicitudin, augue et consequat gravida, urna lectus convallis ipsum, at consectetur est nisi eu purus. Cras ut nibh condimentum ex sollicitudin euismod. Maecenas vulputate eros orci, a hendrerit mauris blandit ut. Praesent ac molestie lectus. In rhoncus ac libero eu mollis. Vivamus rutrum fermentum massa. Nulla id nulla et arcu dapibus ullamcorper porttitor eu leo. Fusce odio lorem, facilisis dictum erat vel, semper sagittis turpis.<br /><br />

									Ut eget ante erat. Curabitur in leo nec dolor pharetra cursus. Fusce in est lorem. Suspendisse quis felis auctor, eleifend elit nec, egestas neque. Donec vel magna eget urna eleifend luctus. Suspendisse auctor sit amet augue vel varius. Mauris blandit magna euismod mi volutpat luctus. Praesent malesuada massa a dolor tristique consectetur. Proin lectus arcu, dignissim eget augue quis, aliquam feugiat nisl. Aliquam facilisis tempus sapien, non pellentesque velit finibus ac. Sed tincidunt sollicitudin aliquet. In nec odio eu mauris aliquam lacinia. Pellentesque iaculis tellus ut ante auctor, vitae egestas velit bibendum. Cras nec dui a justo auctor pretium. Ut quis neque a nulla vehicula lobortis. Vestibulum efficitur lacinia quam a tristique.<br /><br />

			</div>
			<div style="clear:both;"></div>